if [ -f ~/antigen/antigen.zsh ]; then
    source ~/antigen/antigen.zsh
elif [ -f /usr/share/zsh-antigen/antigen.zsh ]; then
    source /usr/share/zsh-antigen/antigen.zsh
fi

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle pyenv

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme jeremyFreeAgent/oh-my-zsh-powerline-theme powerline

# Tell antigen that you're done.
antigen apply

source ~/.zalias

fpath=(~/.zfunctions $fpath)
autoload gproxy 
