if [ -f ~/.antigen/antigen.zsh ]; then
    source ~/.antigen/antigen.zsh
elif [ -f /usr/share/zsh-antigen/antigen.zsh ]; then
    source /usr/share/zsh-antigen/antigen.zsh
else
    git clone https://github.com/zsh-users/antigen.git ~/.antigen
    source ~/.antigen/antigen.zsh
fi

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle pyenv

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# [ theme - powerline ]
# antigen theme jeremyFreeAgent/oh-my-zsh-powerline-theme powerline

# [ theme - punctual ]

## [ part ]
PUNCTUAL_SHOW_USER="false";

## [ color ]
PUNCTUAL_TIMESTAMP_COLOUR="red";
PUNCTUAL_HOSTNAME_COLOUR="blue";
PUNCTUAL_CURRENT_DIR_COLOUR="magenta";
PUNCTUAL_GIT_COLOUR="cyan";

## [ prompt ]
PUNCTUAL_PROMPT="\u262f ";

antigen theme dannynimmo/punctual-zsh-theme punctual


# Tell antigen that you're done.
antigen apply

source ~/.zalias

fpath=(~/.zfunctions $fpath)
autoload gproxy 
autoload svndiff

# Disable auto title feature, so byobu can keep the window title
export DISABLE_AUTO_TITLE="true"

